#!/usr/bin/env python3
"""Render mass/momentum probe results to an MP4 diagnostic video.

Input files are generated by `mass_momentum_probe.py`.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FFMpegWriter


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render mass probe CSV/NPZ to MP4."
    )
    parser.add_argument("--csv", type=Path, required=True)
    parser.add_argument("--out-mp4", type=Path, required=True)
    parser.add_argument("--fps", type=int, default=30)
    parser.add_argument("--title", default="Mass/Momentum Probe")
    return parser.parse_args()


def load_csv(path: Path) -> dict[str, np.ndarray]:
    with path.open("r", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
    if not rows:
        raise ValueError(f"No rows in {path}")
    keys = rows[0].keys()
    data: dict[str, np.ndarray] = {}
    for key in keys:
        data[key] = np.asarray([float(r[key]) for r in rows], dtype=np.float32)
    return data


def main() -> int:
    args = parse_args()
    args.out_mp4.parent.mkdir(parents=True, exist_ok=True)

    data = load_csv(args.csv.resolve())
    frames = data["frame"].astype(np.int32)

    fig, axes = plt.subplots(2, 1, figsize=(10, 7), dpi=120, sharex=True)
    ax_pos, ax_mom = axes

    x_min = min(float(np.min(data["body_x"])), float(np.min(data["obj_x"])))
    x_max = max(float(np.max(data["body_x"])), float(np.max(data["obj_x"])))
    px_min = min(
        float(np.min(data["p_total_x"])),
        float(np.min(data["p_total_y"])),
        float(np.min(data["p_total_z"])),
    )
    px_max = max(
        float(np.max(data["p_total_x"])),
        float(np.max(data["p_total_y"])),
        float(np.max(data["p_total_z"])),
    )

    ax_pos.set_xlim(int(frames[0]), int(frames[-1]))
    ax_pos.set_ylim(x_min - 0.02, x_max + 0.02)
    ax_pos.set_ylabel("x position")
    ax_pos.grid(True, alpha=0.3)

    ax_mom.set_xlim(int(frames[0]), int(frames[-1]))
    ax_mom.set_ylim(px_min - 0.05, px_max + 0.05)
    ax_mom.set_ylabel("total momentum")
    ax_mom.set_xlabel("frame")
    ax_mom.grid(True, alpha=0.3)

    line_body_x, = ax_pos.plot([], [], label="Rigid body x", color="tab:blue", linewidth=2.0)
    line_obj_x, = ax_pos.plot([], [], label="Object COM x", color="tab:orange", linewidth=2.0)
    ax_pos.legend(loc="upper right")

    line_px, = ax_mom.plot([], [], label="P_total_x", color="tab:green", linewidth=1.8)
    line_py, = ax_mom.plot([], [], label="P_total_y", color="tab:red", linewidth=1.8)
    line_pz, = ax_mom.plot([], [], label="P_total_z", color="tab:purple", linewidth=1.8)
    ax_mom.legend(loc="upper right")

    writer = FFMpegWriter(fps=args.fps, metadata={"title": args.title}, bitrate=4000)
    with writer.saving(fig, str(args.out_mp4.resolve()), dpi=120):
        for i in range(frames.shape[0]):
            x = frames[: i + 1]
            line_body_x.set_data(x, data["body_x"][: i + 1])
            line_obj_x.set_data(x, data["obj_x"][: i + 1])
            line_px.set_data(x, data["p_total_x"][: i + 1])
            line_py.set_data(x, data["p_total_y"][: i + 1])
            line_pz.set_data(x, data["p_total_z"][: i + 1])
            fig.suptitle(f"{args.title} | frame={int(frames[i])}", fontsize=13)
            writer.grab_frame()

    plt.close(fig)
    print(args.out_mp4.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

