#!/usr/bin/env python3
"""Render a clear 3D perspective MP4 for rigid-box vs rope probe runs.

This script is dependency-light: numpy + PIL + ffmpeg.
Input is the `*_scene.npz` generated by:
`newton_import_ir.py --rigid-probe`.
"""

from __future__ import annotations

import argparse
import math
import shutil
import subprocess
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont


BOX_EDGES = (
    (0, 1),
    (0, 2),
    (0, 4),
    (3, 1),
    (3, 2),
    (3, 7),
    (5, 1),
    (5, 4),
    (5, 7),
    (6, 2),
    (6, 4),
    (6, 7),
)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Render a 3D perspective rigid-box vs rope MP4.")
    p.add_argument("--scene-npz", type=Path, required=True, help="*_scene.npz from rigid probe")
    p.add_argument("--out-mp4", type=Path, required=True)
    p.add_argument("--ir-npz", type=Path, default=None, help="Optional IR npz for spring_edges overlay")
    p.add_argument("--fps", type=float, default=30.0)
    p.add_argument("--size", type=int, nargs=2, default=(1280, 720), metavar=("W", "H"))
    p.add_argument("--frame-start", type=int, default=0)
    p.add_argument("--max-frames", type=int, default=120)
    p.add_argument("--max-points", type=int, default=1800)
    p.add_argument("--point-radius", type=int, default=2)
    p.add_argument("--spring-stride", type=int, default=24, help="Draw every k-th spring edge")
    p.add_argument("--fov-deg", type=float, default=42.0)
    p.add_argument("--camera-dir", type=float, nargs=3, default=(1.0, 0.55, 1.1), metavar=("X", "Y", "Z"))
    p.add_argument("--distance-scale", type=float, default=3.4, help="Camera distance scale against object span")
    p.add_argument("--track-smooth", type=float, default=0.86, help="EMA smoothing for tracked camera center")
    p.add_argument("--keep-frames", action="store_true")
    return p.parse_args()


def _load_font(size: int) -> ImageFont.ImageFont:
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    ]
    for c in candidates:
        try:
            return ImageFont.truetype(c, size=size)
        except Exception:
            continue
    return ImageFont.load_default()


def _encode_mp4(frames_dir: Path, fps: float, out_mp4: Path) -> None:
    cmd = [
        "ffmpeg",
        "-y",
        "-framerate",
        f"{float(fps)}",
        "-start_number",
        "0",
        "-i",
        str(frames_dir / "%d.png"),
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        "-crf",
        "18",
        "-movflags",
        "+faststart",
        str(out_mp4),
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def _norm(v: np.ndarray) -> np.ndarray:
    n = float(np.linalg.norm(v))
    if not math.isfinite(n) or n <= 1e-12:
        return np.asarray([1.0, 0.0, 0.0], dtype=np.float64)
    return v / n


def _look_at(eye: np.ndarray, target: np.ndarray, world_up: np.ndarray = np.asarray([0.0, 1.0, 0.0])) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    forward = _norm(target - eye)
    right = np.cross(forward, world_up)
    if float(np.linalg.norm(right)) < 1e-8:
        right = np.cross(forward, np.asarray([0.0, 0.0, 1.0], dtype=np.float64))
    right = _norm(right)
    up = _norm(np.cross(right, forward))
    return right, up, forward


def _quat_to_rotmat_xyzw(q_xyzw: np.ndarray) -> np.ndarray:
    q = np.asarray(q_xyzw, dtype=np.float64).reshape(-1)
    x, y, z, w = float(q[0]), float(q[1]), float(q[2]), float(q[3])
    n = math.sqrt(x * x + y * y + z * z + w * w)
    if not math.isfinite(n) or n <= 0.0:
        return np.eye(3, dtype=np.float64)
    x /= n
    y /= n
    z /= n
    w /= n
    xx, yy, zz = x * x, y * y, z * z
    xy, xz, yz = x * y, x * z, y * z
    wx, wy, wz = w * x, w * y, w * z
    return np.asarray(
        [
            [1.0 - 2.0 * (yy + zz), 2.0 * (xy - wz), 2.0 * (xz + wy)],
            [2.0 * (xy + wz), 1.0 - 2.0 * (xx + zz), 2.0 * (yz - wx)],
            [2.0 * (xz - wy), 2.0 * (yz + wx), 1.0 - 2.0 * (xx + yy)],
        ],
        dtype=np.float64,
    )


def _box_corners_world(pos: np.ndarray, quat_xyzw: np.ndarray, hx: float, hy: float, hz: float) -> np.ndarray:
    corners_body = np.asarray(
        [
            [-hx, -hy, -hz],
            [-hx, -hy, +hz],
            [-hx, +hy, -hz],
            [-hx, +hy, +hz],
            [+hx, -hy, -hz],
            [+hx, -hy, +hz],
            [+hx, +hy, -hz],
            [+hx, +hy, +hz],
        ],
        dtype=np.float64,
    )
    R = _quat_to_rotmat_xyzw(quat_xyzw)
    return corners_body @ R.T + np.asarray(pos, dtype=np.float64).reshape(1, 3)


def _project(points_world: np.ndarray, eye: np.ndarray, right: np.ndarray, up: np.ndarray, forward: np.ndarray, fx: float, fy: float, cx: float, cy: float, near: float = 1e-4) -> tuple[np.ndarray, np.ndarray]:
    rel = points_world.astype(np.float64) - eye.reshape(1, 3)
    x_cam = rel @ right
    y_cam = rel @ up
    z_cam = rel @ forward
    valid = z_cam > near
    px = cx + fx * (x_cam / np.maximum(z_cam, near))
    py = cy - fy * (y_cam / np.maximum(z_cam, near))
    out = np.stack([px, py], axis=1)
    return out, valid


def _draw_disc(draw: ImageDraw.ImageDraw, x: float, y: float, r: int, color: tuple[int, int, int]) -> None:
    xi = int(round(x))
    yi = int(round(y))
    rr = max(1, int(r))
    draw.ellipse((xi - rr, yi - rr, xi + rr, yi + rr), fill=color)


def main() -> int:
    args = parse_args()
    scene_npz = args.scene_npz.resolve()
    out_mp4 = args.out_mp4.resolve()
    out_mp4.parent.mkdir(parents=True, exist_ok=True)

    with np.load(scene_npz, allow_pickle=False) as data:
        q_obj = np.asarray(data["particle_q_object"], dtype=np.float32)  # [F,N,3]
        body_q = np.asarray(data["body_q"], dtype=np.float32)  # [F,7]
        hx = float(np.asarray(data["rigid_hx"]).ravel()[0])
        hy = float(np.asarray(data["rigid_hy"]).ravel()[0])
        hz = float(np.asarray(data["rigid_hz"]).ravel()[0])
        sim_dt = float(np.asarray(data["sim_dt"]).ravel()[0]) if "sim_dt" in data.files else 1.0 / max(float(args.fps), 1e-6)
        substeps_per_frame = int(np.asarray(data["substeps_per_frame"]).ravel()[0]) if "substeps_per_frame" in data.files else 1

    if q_obj.ndim != 3 or q_obj.shape[-1] != 3:
        raise ValueError(f"Unexpected particle_q_object shape: {q_obj.shape}")
    if body_q.ndim != 2 or body_q.shape[0] != q_obj.shape[0] or body_q.shape[1] < 7:
        raise ValueError(f"Unexpected body_q shape: {body_q.shape}")

    n_total = int(q_obj.shape[0])
    frame_start = max(0, int(args.frame_start))
    frame_end = n_total
    if args.max_frames is not None:
        frame_end = min(frame_end, frame_start + max(1, int(args.max_frames)))
    if frame_start >= frame_end:
        raise ValueError(f"Empty frame range: start={frame_start}, end={frame_end}")
    q_obj = q_obj[frame_start:frame_end]
    body_q = body_q[frame_start:frame_end]
    frames = int(q_obj.shape[0])

    n_obj = int(q_obj.shape[1])
    if n_obj > int(args.max_points):
        idx = np.linspace(0, n_obj - 1, num=int(args.max_points), dtype=np.int64)
        q_vis = q_obj[:, idx, :]
    else:
        idx = None
        q_vis = q_obj

    spring_edges = None
    if args.ir_npz is not None:
        with np.load(args.ir_npz.resolve(), allow_pickle=False) as ir:
            if "spring_edges" in ir and "num_object_points" in ir:
                edges = np.asarray(ir["spring_edges"], dtype=np.int32)
                n_ir_obj = int(np.asarray(ir["num_object_points"]).ravel()[0])
                keep = (edges[:, 0] < n_ir_obj) & (edges[:, 1] < n_ir_obj)
                edges = edges[keep]
                if idx is not None:
                    remap = -np.ones((n_ir_obj,), dtype=np.int32)
                    remap[idx] = np.arange(idx.shape[0], dtype=np.int32)
                    a = remap[edges[:, 0]]
                    b = remap[edges[:, 1]]
                    ok = (a >= 0) & (b >= 0)
                    edges = np.stack([a[ok], b[ok]], axis=1)
                if edges.shape[0] > 0:
                    spring_edges = edges[:: max(1, int(args.spring_stride))].copy()

    w, h = int(args.size[0]), int(args.size[1])
    fov = float(args.fov_deg) * math.pi / 180.0
    fy = (h * 0.5) / max(math.tan(fov * 0.5), 1e-6)
    fx = fy
    cx, cy = (w * 0.5), (h * 0.5)
    bg = (248, 250, 253)
    rope_color = (53, 111, 183)
    rope_line = (125, 160, 208)
    box_color = (216, 61, 54)
    com_color = (232, 173, 29)
    text_color = (25, 29, 38)

    font = _load_font(21)
    small_font = _load_font(18)
    tiny_font = _load_font(15)

    cam_dir = _norm(np.asarray(args.camera_dir, dtype=np.float64))
    alpha = float(args.track_smooth)
    cam_center = None
    cam_dist = None

    frames_dir = out_mp4.parent / f".{out_mp4.stem}_frames"
    if frames_dir.exists():
        shutil.rmtree(frames_dir)
    frames_dir.mkdir(parents=True, exist_ok=True)

    prev_body = None
    frame_dt = max(float(sim_dt) * max(substeps_per_frame, 1), 1e-12)
    for f in range(frames):
        pts = q_vis[f].astype(np.float64)
        bpos = body_q[f, 0:3].astype(np.float64)
        bquat = body_q[f, 3:7].astype(np.float64)
        com = np.mean(pts, axis=0)
        dist_bc = float(np.linalg.norm(bpos - com))

        # Tracking target and distance.
        target = 0.5 * (bpos + com)
        q05 = np.quantile(pts, 0.05, axis=0)
        q95 = np.quantile(pts, 0.95, axis=0)
        rope_span = float(np.linalg.norm(q95 - q05))
        local_span = max(0.10, rope_span + dist_bc + 2.5 * max(hx, hy, hz))
        local_dist = max(0.30, float(args.distance_scale) * local_span)
        if cam_center is None:
            cam_center = target
            cam_dist = local_dist
        else:
            cam_center = alpha * cam_center + (1.0 - alpha) * target
            cam_dist = alpha * cam_dist + (1.0 - alpha) * local_dist

        eye = cam_center - cam_dir * cam_dist
        right, up, forward = _look_at(eye, cam_center)

        # Prepare drawing canvas.
        img = Image.new("RGB", (w, h), color=bg)
        draw = ImageDraw.Draw(img)

        # Box.
        corners = _box_corners_world(bpos, bquat, hx, hy, hz)
        corners_px, corners_valid = _project(corners, eye, right, up, forward, fx, fy, cx, cy)
        for i, j in BOX_EDGES:
            if bool(corners_valid[i]) and bool(corners_valid[j]):
                draw.line(
                    (
                        float(corners_px[i, 0]),
                        float(corners_px[i, 1]),
                        float(corners_px[j, 0]),
                        float(corners_px[j, 1]),
                    ),
                    fill=box_color,
                    width=4,
                )

        # Optional sparse spring structure lines.
        if spring_edges is not None and spring_edges.shape[0] > 0:
            pts_px, pts_valid = _project(pts, eye, right, up, forward, fx, fy, cx, cy)
            for a, b in spring_edges:
                if bool(pts_valid[a]) and bool(pts_valid[b]):
                    draw.line(
                        (
                            float(pts_px[a, 0]),
                            float(pts_px[a, 1]),
                            float(pts_px[b, 0]),
                            float(pts_px[b, 1]),
                        ),
                        fill=rope_line,
                        width=1,
                    )
        else:
            pts_px, pts_valid = _project(pts, eye, right, up, forward, fx, fy, cx, cy)

        # Rope particles (draw far -> near).
        rel = pts - eye.reshape(1, 3)
        z_cam = rel @ forward
        order = np.argsort(-z_cam)
        r = max(1, int(args.point_radius))
        for i in order:
            if not bool(pts_valid[i]):
                continue
            x = float(pts_px[i, 0])
            y = float(pts_px[i, 1])
            if x < -4 or x > (w + 4) or y < -4 or y > (h + 4):
                continue
            _draw_disc(draw, x, y, r, rope_color)

        # Body center and rope COM markers.
        com_px, com_valid = _project(com.reshape(1, 3), eye, right, up, forward, fx, fy, cx, cy)
        body_px, body_valid = _project(bpos.reshape(1, 3), eye, right, up, forward, fx, fy, cx, cy)
        if bool(com_valid[0]):
            _draw_disc(draw, float(com_px[0, 0]), float(com_px[0, 1]), 5, com_color)
        if bool(body_valid[0]):
            _draw_disc(draw, float(body_px[0, 0]), float(body_px[0, 1]), 5, box_color)
        if bool(com_valid[0]) and bool(body_valid[0]):
            draw.line(
                (
                    float(body_px[0, 0]),
                    float(body_px[0, 1]),
                    float(com_px[0, 0]),
                    float(com_px[0, 1]),
                ),
                fill=(95, 95, 105),
                width=2,
            )

        # HUD text.
        speed = 0.0
        if prev_body is not None:
            speed = float(np.linalg.norm(bpos - prev_body) / frame_dt)
        prev_body = bpos.copy()
        title = "Rigid Box vs Rope Collision (Newton Importer CLI Probe)"
        subtitle = f"frame {f + 1}/{frames} | body_speed={speed:.3f} m/s | dist(body, COM)={dist_bc:.4f} m"
        legend = "Blue=Rope particles  Red=Rigid box  Yellow=Rope COM"
        draw.rectangle((16, 14, min(w - 16, 1100), 98), fill=(255, 255, 255))
        draw.text((28, 20), title, fill=text_color, font=font)
        draw.text((28, 52), subtitle, fill=text_color, font=small_font)
        draw.text((28, 76), legend, fill=(56, 64, 79), font=tiny_font)

        img.save(frames_dir / f"{f}.png", optimize=False)

    _encode_mp4(frames_dir=frames_dir, fps=float(args.fps), out_mp4=out_mp4)
    if not args.keep_frames:
        shutil.rmtree(frames_dir, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
